# https://golangci-lint.run/usage/quick-start/
run:
  concurrency: 4
  timeout: 5m
  build-tags:
    - test
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck