apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |
      This example has two sinks.

      * When using two sinks, you should put the most reliable first in the list, if the message cannot be delivered,
        then subsequent sinks will get the message.
  creationTimestamp: null
  name: 301-two-sinks
spec:
  steps:
  - cat: {}
    name: main
    sinks:
    - log: {}
      name: a
    - log: {}
      name: b
    sources:
    - kafka:
        topic: input-topic
